### ISSUE TITLE
Don't create .prob files for combined files

### ISSUE THREAD

**Issue by nedbat** [edx/i18n-tools#36]
When a problem happens in a .po file, the problem is reported both in the original file, and where it appears in the combined file, like this:
```
./conf/locale/pt_BR/LC_MESSAGES/django.prob
./conf/locale/pt_BR/LC_MESSAGES/mako-studio.prob
```
Don't do that.

**Comment by nedbat** [comment]
This is in JIRA: https://openedx.atlassian.net/projects/LOC/issues/LOC-96

**Comment by sarina** [comment]
you know that's just because I'm lazy. It's because the duplicate reporting has to happen after all the merging occurs, but the problem catching logic occurs at some point that assumes that the interstitial files have been cleared, but they can't be cleared, because of the duplicate logic... sigh. IDK. I forgot the exact _why_ this occurs, but I can promise you that it was introduced in https://github.com/edx/i18n-tools/pull/15 (which helpfully notes that you gestured a thumbs up while wearing headphones so perhaps it was not adequately reviewed... :grinning: )
